In [ ]:
#------------------------------------------------------------------------------
#Nome: Alexandre Henrique Silva de Araujo
#Universidade Mogi das Cruzes
#Data: 21/08/2026 - Sexta-Feira
#Prazo: 23 de agosto de 2026 (Sexta-Feira)
#Exercicios_Python (Numpy, Scipy, Pandas, Matplot)
#------------------------------------------------------------------------------

# Exercicios de Numpy

## Crie um array unidimensional de 50 elementos contendo números inteiros aleatórios entre 10 e 100.

In [2]:
import random # importando a biblioteca ramdom permite gerar numeros aleatorios

#Usamos o array juntar varios valores dentro de uma unica variavel.
#Trazemos a função da biblioteca + o randint para gerar um numero aleatorio entre a 10
# e por fim usamos "range(50)]" para ser repetido em 50 vezes, gerando 50 elementos.
array = [random.randint(10, 100) for _ in range(50)]

#imprimir codigo
print(array)

[72, 22, 49, 70, 31, 45, 91, 79, 14, 70, 75, 21, 24, 58, 100, 12, 33, 45, 64, 99, 60, 78, 24, 42, 47, 23, 60, 88, 10, 98, 35, 10, 98, 76, 84, 78, 61, 98, 26, 14, 44, 63, 26, 60, 63, 66, 90, 45, 89, 17]


## Gere uma matriz 4x4 com números inteiros de 1 a 16 e extraia a última linha

In [30]:
import numpy as np #Usamos o numpy e batizamos para "np" para facilitar o uso de suas funções

matriz = np.arange(1, 17).reshape(4, 4)
#Usamos uma das funcionalidades do np: Arange, que permite formar os numeros de 1 a 16 numeros(OBS: o N° 17 nao se inclui)
#E usamos o "reshape(4, 4)" para organizar a nossa matriz de 4x4, totalizando 16 numeros no total
print("Matriz Completa:")
print(matriz)

#A ultima linha, tecnicamente representado por "(-1) seleciona a ultima linha da matriz, assim como o nome sugere"
#Já o "(:) significa todas as colunas"

#Ou seja, a variavel "ultima_linha" seleciona a ultima linha e todas as colunas existentes
ultima_linha = matriz[-1, :]

#por fim, imprimimos a matriz
#(OBS: "\n" faz uma quebra de linha na hora de imprimir o codigo)
print("\nUltima Linha:")
print(ultima_linha)


Matriz Completa
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Ultima Linha:
[13 14 15 16]


## Crie um array de zeros com comprimento 15 e substitua os valores da 5ª a 10ª posicão por 1.

In [1]:
import numpy as np

#Aqui chamamos outra funlção do numpy "zeros" com a finalidade de criar uma array contendo 15 valores iguais a 0

array = np.zeros(15, dtype=int)

# já o "dtype=int)" define os valores do array que serão do tipo int, ou seja, inteiro.

array[4:10] = 1

# Selecionamos as posições do índice 4 até o índice 9 e substituímos seus valores por 1
# (OBS: o índice 10 não é incluído)

print(array)

[0 0 0 0 1 1 1 1 1 1 0 0 0 0 0]


## Gere um array de 100 Números inteiros aleatorios e encontre a mediana e a moda dos valores.

In [3]:
import numpy as np
from collections import Counter

#Importamos duas bibliotecas "numpy" e "Colletions" com o "counter"
#Ela permite contar quantas vezes cada valor aparece

array = np.random.randint(0,101,100)
#Array de 100 numeros aleatorios de 0 a 100

mediana = np.median(array)
#Usamos a função do numpy "median" para calcular a mediana

contagem = Counter(array) #Usamos o coutenter quantas vezes cada numero aparece
moda = contagem.most_common(1)[0][0]
#usamos a função "most_common" para encontrar o valor que mais se repete
#Os "[0][0]" são usados para acessar o valor encontrado dentro do resultado


print("Array:", array)
print("Mediana:", mediana)
print("Moda:", moda)

Array: [ 99  27  53  13  81  26  85  24  95  62  21  81   6  81  32  35  10   1
  87 100  94  64  60  41   6   3  83  93  33  75  48   6   9  76  27  22
 100  37  24  10  42  56  21  72  30  93  57  62  13  31  29  76  12   1
  30  32   3  61   2  49  54  27  54   1  84  91  38  29  54  51  70  23
  91  77   2  73  11   0  43  99  10   0  58  14  98  19  49  41  91  36
  27  55  88  30  72   4  58  13  53  28]
Mediana: 41.0
Moda: 27


## Crie um array de 20 elementos contendo numeros entre 1 e 100 e substituatodos os valores multiplos de 3 por -3

In [9]:
import numpy as np

array = np.random.randint(1, 101, 20)
#Array de 20 numeros aleatorios de 1 e 100

array[array % 3 == 0] = -3
# Usamos o "%" para verificar o resto da divisão dos valores por 3
# Quando o resto for igual a 0, significa que o valor é múltiplo de 3
# Então substituímos esses valores por -3

print(array)

[ 1 89 74 -3 50 -3 55  7 40  4 62 -3 19 10 -3 47 41  7 71 37]


## Gere uma matriz 5x5 de numeros aleatorios entre 0 e 1 e encontre a soma de cada coluna.

In [41]:
import numpy as np

#Matriz de 5x5 com numeros de 1 a 100
matriz = np.random.randint(1, 101, (5, 5))

somar_colunas = matriz.sum(axis=0)
# Usamos o "sum" para realizar a soma dos valores da matriz
# O "axis=0" indica que a soma será realizada por coluna

print("Matriz:")
print(f"\n {matriz}")

print("\n Soma de cada coluna:")
print(somar_colunas)

Matriz:

 [[63 88 63 29 54]
 [62 22 49 82  4]
 [28 39 26 20 69]
 [23 71 62 17 51]
 [52 70 93 81 43]]

 Soma de cada coluna:
[228 290 293 229 221]


## Crie dois arrays de numeros aleatorios e encontre a correlacao entre eles

In [44]:
import numpy as np

#duas arrays com 10 numeros aleatorios de 0 e 1
array1 = np.random.rand(10)
array2 = np.random.rand(10)

correlacao = np.corrcoef(array1, array2)[0, 1]
# Usamos o "corrcoef" para calcular a correlação entre os dois arrays
# O "[0, 1]" seleciona o valor da correlação entre o primeiro e o segundo array

print("Array 1:", array1)
print("\n Array 2:", array2)
print("\n Correlação:", correlacao)

Array 1: [0.78797853 0.45565412 0.69223633 0.33785552 0.30643976 0.302633
 0.60247183 0.31544298 0.32550741 0.20307385]

 Array 2: [0.38195885 0.99035936 0.50636617 0.80609094 0.70806537 0.72931859
 0.75875662 0.25959443 0.13323089 0.45374932]

 Correlação: 0.016344947629142344


## Gere uma matriz 3x3 com numeros inteiros aleatorios e eleve todos os seus elementos ao quadrado.

In [48]:
import numpy as np

matriz = np.random.randint(1, 10, (3, 3))

# Criamos uma matriz 3x3 com números inteiros aleatórios entre 1 e 9

matriz_quadrado = matriz ** 2

# Elevamos todos os valores da matriz ao quadrado usando o operador "**"

print("Matriz original:")

print(matriz)

print("\n Matriz ao quadrado:")

print(matriz_quadrado)

# Por fim, imprimimos a matriz original e a matriz com todos os seus valores elevados ao quadrado

Matriz original:
[[5 6 7]
 [1 3 5]
 [1 5 5]]

 Matriz ao quadrado:
[[25 36 49]
 [ 1  9 25]
 [ 1 25 25]]


## Crie um array com 10 numeros aleatorios e normalize seus valores entre 0 e 1.

In [47]:
import numpy as np

# Criamos um array com 10 números aleatórios entre 0 e 1
array = np.random.rand(10)


array_normalizado = (array - array.min()) / (array.max() - array.min())
# Usamos o "min" para encontrar o menor valor do array
# E usamos o "max" para encontrar o maior valor do array
# Depois, aplicamos uma fórmula para normalizar os valores entre 0 e 1

print("Array original:")
print(array)

print("\n Array normalizado:")
print(array_normalizado)


Array original:
[0.57750795 0.7145124  0.42815563 0.67187447 0.4739197  0.2158674
 0.91701986 0.49048996 0.54799266 0.60383273]

 Array normalizado:
[0.5157802  0.71117914 0.30277043 0.65036792 0.36804021 0.
 1.         0.39167311 0.4736848  0.55332521]


## Crie uma matriz identidade 6x6 e substitua a diagonal principal por valores crescentes de 1 a 6.

In [46]:
import numpy as np

matriz = np.eye(6)
# Usamos o "eye" para criar uma matriz identidade 6x6
# A matriz identidade possui 1 na diagonal principal e 0 nos demais elementos

matriz[np.diag_indices_from(matriz)] = np.arange(1, 7)
# Usamos o "diag_indices_from" para selecionar as posições da diagonal principal
# Depois usamos o "arange" para gerar os valores de 1 a 6
# Por fim, substituímos os valores da diagonal principal pelos valores de 1 a 6

print(matriz)


[[1. 0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0. 0.]
 [0. 0. 3. 0. 0. 0.]
 [0. 0. 0. 4. 0. 0.]
 [0. 0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 0. 6.]]


## Gere um array de 100 numeros inteiros e encontre o valor que mais se repete no array.

In [45]:
import numpy as np

array = np.random.randint(1, 101, 100)
# Criamos um array com 100 números inteiros aleatórios entre 1 e 100

valores, contagem = np.unique(array, return_counts=True)
# Usamos o "unique" para encontrar os valores únicos do array
# O "return_counts=True" também retorna quantas vezes cada valor aparece
# Os resultados são armazenados nas variáveis "valores" e "contagem"

valor_mais_repetido = valores[np.argmax(contagem)]
#Usamos o "argmax" para encontrar a posição onde está a maior contagem
# Depois usamos essa posição para encontrar, dentro de "valores", o número que mais se repete

print("Array:", array)
print("Valor que mais se repete:", valor_mais_repetido)


Array: [ 83  57  86  87  11  81   7  70   7  40  11  61  12   2  59  34  54  63
  11  67  75  66  12  91  86  54   2  54  37  57  18  93  15  54  88  76
  72  28  62  67   8  14  41   4  96  67  33  13  35  19  41  91  55  71
  81  42  80  28   4  33  28  44  11  42   9  94  60  12  74 100  10  74
  76  75  56  14   9  59  87   4  23  13  73  10  94  53  13  52  90  14
  54  49  15  17  77  22  11  40  56  61]
Valor que mais se repete: 11


## Crie uma matriz 4x4 e substitua os valores da diagonal principal por 7

In [12]:
import numpy as np

#matrix 4x4
matriz = np.random.randint(1, 101, (4, 4))

np.fill_diagonal(matriz, 7)
# Usamos o "fill_diagonal" para substituir todos os valores da diagonal principal por 7


print("Matriz original:")
print(matriz)

Matriz original:
[[ 7 45 48 90]
 [96  7 17  9]
 [20 72  7 62]
 [13 93 41  7]]


## Crie um array contendo os 10 primeiros numeros pares e calcule sua soma cumulativa.


In [ ]:
import numpy as np

array = np.arange(2, 22, 2)
# Usamos o "arange" para criar um array com os números pares de 2 até 20
# O primeiro 2 indica o valor inicial, o 22 é o limite que não será incluído
# e o último 2 indica que os valores serão adicionados de 2 em 2

soma_cumulativa = np.cumsum(array)
# Usamos o "cumsum" para calcular a soma cumulativa dos valores do array
# Ou seja, cada valor é somado com todos os valores anteriores

print("Array:", array)
print("Soma cumulativa:", soma_cumulativa)


## Calcule a diferenca entre dois arrays de numeros aleatorios de mesmo comprimento e encontre a media das diferencas.

In [50]:
import numpy as np

array1 = np.random.rand(10) # Criamos um array com 10 números aleatórios entre 0 e 1
array2 = np.random.rand(10)# Criamos um array com 10 números aleatórios entre 0 e 1

diferenca = np.abs(array1 - array2)
# Subtraímos os valores dos dois arrays e usamos o "abs" para transformar...
# todos os resultados em valores positivos, obtendo a diferença entre eles

media_diferenca = np.mean(diferenca)
# Usamos o "mean" para calcular a média de todas as diferenças encontradas

print("Array 1:", array1)
print("Array 2:", array2)
print("Diferença:", diferenca)
print("Média das diferenças:", media_diferenca)


Array 1: 4
Array 2: 4
Diferença: 0
Média das diferenças: 0.0


## Gere um array contendo 20 numeros e substitua todos os valores maiores que 50 por 50.

In [14]:
import numpy as np

array = np.random.randint(1, 101, 20) # Geramos um array com 20 números inteiros aleatórios entre 1 e 100

array[array > 50] = 50
# Selecionamos todos os valores maiores que 50 e substituímos esses valores por 50
# Em outras palavras, ele verifica cada elemento do array e identifica quais que são maiores do que 50

print("Array original:", array)

Array original: [17 29 50 10  5 50 31 22 50 38 50 50 50 50 50 50 50 50 38 50]


## Crie um array unidimensional e reorganize seus valores em uma matriz 3x4.

In [34]:
import numpy as np

array = np.random.randint(1, 101, 12) # Criamos um array com 12 números inteiros aleatórios entre 1 e 100

matriz = array.reshape(3, 4)

#Aqui usamos o reshape(3,4) para organizar os valores do array em uma matriz de 3 linhas e 4 colunas

print("Array original:")
print(array)
print("\n Matriz reorganizada:")
print(matriz)


Array original:
[76 37 61 36 93 63 59 50 84 59 56 62]

 Matriz reorganizada:
[[76 37 61 36]
 [93 63 59 50]
 [84 59 56 62]]


## Gere uma matriz 4x4 de numeros inteiros aleatorios e multiplique cada valor por sua posicao na matriz.

In [36]:
import numpy as np

matriz = np.random.randint(1, 101, (4, 4))
#novamente com matriz, criamos uma matriz de 4x4 entre numeros de 100

matriz_multiplicada = matriz * np.arange(1, 17).reshape(4, 4)
#Usamos uma das funcionalidades do np: Arange, que permite formar os numeros de 1 a 16 numeros(OBS: o N° 17 nao se inclui)
#E usamos o "reshape(4, 4)" para organizar a nossa matriz de 4x4, totalizando 16 numeros no total

#Todavia, multiplicamos a variavel "matriz" com os seus valores originais vezes o valor correspondente a segunda matriz
#Diante isso, encontramos a Matriz "original" multiplicada pelo valor da segunda matriz

print("Matriz original:")
print(f"\n {matriz}")

Matriz original:

 [[10 27  6 29]
 [16 41 23 17]
 [22 69  9 67]
 [64 65 60 94]]


## Crie um array de 10 elementos contendo numeros entre 1 e 100 e substitua todos os valores multiplos de 5 por 0.

In [37]:
import numpy as np

array = np.random.randint(1, 101, 10) # Criamos um array com 10 números inteiros aleatórios entre 1 e 100

array[array % 5 == 0] = 0

#Usamos esse sianl "%" que retornará o resto de uma divisão, para verificar os valores do resto da divisão dos valores por 5
#Enquanto o resto for igual a 0, então o valor é multiplo de 5, e em seguida, substituimos esse valor por 0

print("Array: ", array)


Array:  [ 0 62  0 67 58  0 44  0 16 51]


## Crie dois arrays de numeros inteiros aleatorios de tamanho 20 e calcule o angulo entre eles (produto escalar normalizado).

In [38]:
import numpy as np

#criamos duas arrays com 20 números inteiros aleatórios entre 1 e 100

array1 = np.random.randint(1, 101, 20)
array2 = np.random.randint(1, 101, 20)

#para o tamanho, usamos umas funções para calcular o tamanho dos array's
#np.linalg.norm = calcula o tamanho de um vetor.
tamanho_array1 = np.linalg.norm(array1)
tamanho_array2 = np.linalg.norm(array2)

#aqui usamos np.dot para o calcular o produto interno entre os dois arrays
produto_escalar = np.dot(array1, array2)

#Arccos é uma função para o calcular o angulo entre os arrays e dividimos pelo o produto conforme a formula para encontrar o angulo entre os vetores
# Tecnicamente falando, o arccos calcula o cosseno de um valor
angulo_rad = np.arccos(produto_escalar / (tamanho_array1 * tamanho_array2))

#np.degrees é usado para o convereter o angulo dos arrays de radianos para graus.
# Tecnicamente falando, ele converte um angulo de radianos para graus

angulo_graus = np.degrees(angulo_rad)

print("Array 1:", array1)
print("Array 2:", array2)
print("Ângulo entre os arrays em radianos:", angulo_rad)
print("Ângulo entre os arrays em graus:", angulo_graus)



Array 1: [31 77 20 71 14 80 27 36 79 43 21 55 30 67 59 30 76 64 79 96]
Array 2: [88 17 17 36 98 11 44 98 58 66 80 41 45 22 75 80 22 52 71 20]
Ângulo entre os arrays em radianos: 0.8089318984271724
Ângulo entre os arrays em graus: 46.348383693382374


## Crie uma matriz de numeros inteiros e encontre o valor mınimo de cada linha.


In [18]:
import numpy as np

#matriz 3x3 com numeros de 1 a 100 (ordem aleatoria)
matriz = np.random.randint(1, 101, (3, 3))

valor_minimo = np.min(matriz, axis=1)
#Usamos duas funções nessa codificação: Min e axis
#O "np.min" é usado para encontrar os menores numeros da matriz
#já o "axis=1" indica a procura do menor numero em cada linha
print("Matriz:")
print(matriz)

Matriz:
[[17 86 16]
 [36 98 24]
 [21 22 98]]


# Exercıcios de SciPy

##  Calcule a integral da funcao f(x) = x² sin(x) no intervalo de 0 a π

In [52]:
import numpy as np
from scipy.integrate import quad # Importamos o "quad" da biblioteca SciPy para realizar integrais numericamente

# Criamos a função f(x) = x² * sen(x)
def funcao(x):
    return x**2 * np.sin(x)

#QUAD é uma função do SciPy usada para calcular uma integral definida numericamente.
# Usamos o "quad" para calcular a integral da função no intervalo de 0 até pi
# O primeiro valor retornado é o resultado da integral e o segundo é uma estimativa do erro

integral, erro = quad(funcao, 0, np.pi)
#Como o quad retorna dois valores, usamos "integral, erro = quad(funcao, 0, np.pi)"
#A primeira variavel recebe o resultado integral e a segunda a estimativa de erro

print("Valor da integral:", integral)

Valor da integral: 5.869604401089359


## Resolva a equacao diferencial dy/dx = x − y, com y(0) = 1, no intervalo de 0a 10.

In [53]:
import numpy as np # Usamos o numpy e o batizamos de "np" para facilitar o uso de suas funções

from scipy.integrate import solve_ivp # Importamos a função "solve_ivp" do módulo "integrate" do SciPy para resolver equações diferenciais

# Criamos a função que representa a equação diferencial dy/dx = x - y
def equacao(x, y):
    return x - y

# Definimos o intervalo de x entre 0 e 10
intervalo = (0, 10)

# Definimos a condição inicial y(0) = 1
condicao_inicial = [1]

# Usamos o "solve_ivp" para resolver numericamente a equação diferencial
solucao = solve_ivp(equacao, intervalo, condicao_inicial)

print("Valores de x:")

print(solucao.t)

# O ".t" apresenta os valores de x utilizados durante a resolução da equação

print("\nValores de y:")

print(solucao.y[0])

# O ".y" apresenta os valores de y encontrados para cada valor de x
# O "[0]" seleciona os valores da primeira variável da solução

Valores de x:
[ 0.          0.08707246  0.89912411  1.66864823  2.60007906  3.79023301
  5.3414211   7.43308114 10.        ]

Valores de y:
[1.         0.92029381 0.7131988  1.04582535 1.74879205 2.83567181
 4.35139245 6.43481768 9.00046149]


## Encontre as raızes da funcao f(x) = x 4 − 3x³ + 2 utilizando SciPy

In [ ]:
from scipy.optimize import fsolve # Importamos a função "fsolve" do módulo "optimize" do SciPy para encontrar raízes de funções

# Criamos a função f(x) = x⁴ - 3x³ + 2
def funcao(x):
    return x**4 - 3*x**3 + 2

# Usamos o "fsolve" para encontrar as raízes da função


raiz1 = fsolve(funcao, -1)

raiz2 = fsolve(funcao, 1)

raiz3 = fsolve(funcao, 3)

# Os valores "-1", "1" e "3" são valores iniciais utilizados para encontrar as raízes

print("Raízes da função:")

print(raiz1)

print(raiz2)

print(raiz3)

# Use a funcao de otimizacao de SciPy para maximizar f(x) = −x 2+ 4x+ 1.


In [ ]:
from scipy.optimize import minimize_scalar # Importamos a função "minimize_scalar" do módulo "optimize" do SciPy para encontrar o menor valor de uma função

# Criamos a função f(x) = -x² + 4x + 1
def funcao(x):
    return -x**2 + 4*x + 1

# Como o "minimize_scalar" procura o menor valor, usamos o sinal negativo...
# para encontrar o maior valor da função
def funcao_negativa(x):
    return -funcao(x)

# Usamos o "minimize_scalar" para encontrar o valor de x que maximiza a função
resultado = minimize_scalar(funcao_negativa)

# Pegamos o valor de x encontrado pelo método de otimização
x_maximo = resultado.x

# Calculamos o valor máximo da função utilizando o x encontrado
valor_maximo = funcao(x_maximo)

print("Valor de x que maximiza a função:", x_maximo)

print("Valor máximo da função:", valor_maximo)

## Calcule a transformada de Fourier de um sinal composto de sin(2πt) e cos(4πt).

In [54]:
import numpy as np

from scipy.fft import fft, fftfreq # Importamos as funções "fft" e "fftfreq" do módulo "fft" do SciPy

# Criamos um intervalo de tempo entre 0 e 1 segundo com 1000 pontos
t = np.linspace(0, 1, 1000, endpoint=False)

# Criamos o sinal composto pelas funções sen(2πt) e cos(4πt)
sinal = np.sin(2 * np.pi * t) + np.cos(4 * np.pi * t)

# Usamos o "fft" para calcular a Transformada Rápida de Fourier do sinal
transformada = fft(sinal)

# Calculamos as frequências correspondentes aos valores da transformada
frequencias = fftfreq(len(t), 1 / 1000)

# Calculamos a intensidade das frequências presentes no sinal
magnitude = np.abs(transformada)

print("Frequências:")

print(frequencias)

print("\n Magnitude da Transformada de Fourier:")

print(magnitude)

Frequências:
[   0.    1.    2.    3.    4.    5.    6.    7.    8.    9.   10.   11.
   12.   13.   14.   15.   16.   17.   18.   19.   20.   21.   22.   23.
   24.   25.   26.   27.   28.   29.   30.   31.   32.   33.   34.   35.
   36.   37.   38.   39.   40.   41.   42.   43.   44.   45.   46.   47.
   48.   49.   50.   51.   52.   53.   54.   55.   56.   57.   58.   59.
   60.   61.   62.   63.   64.   65.   66.   67.   68.   69.   70.   71.
   72.   73.   74.   75.   76.   77.   78.   79.   80.   81.   82.   83.
   84.   85.   86.   87.   88.   89.   90.   91.   92.   93.   94.   95.
   96.   97.   98.   99.  100.  101.  102.  103.  104.  105.  106.  107.
  108.  109.  110.  111.  112.  113.  114.  115.  116.  117.  118.  119.
  120.  121.  122.  123.  124.  125.  126.  127.  128.  129.  130.  131.
  132.  133.  134.  135.  136.  137.  138.  139.  140.  141.  142.  143.
  144.  145.  146.  147.  148.  149.  150.  151.  152.  153.  154.  155.
  156.  157.  158.  159.  160.  161.  

## Encontre a matriz inversa de uma matriz 5x5 de numeros aleatorios

In [61]:
import numpy as np

from scipy.linalg import inv # Importamos a função "inv" do módulo "linalg" do SciPy para calcular a matriz inversa

matriz = np.random.randint(1, 101, (5, 5))

# Criamos uma matriz 5x5 com números inteiros aleatórios entre 1 e 100


matriz_inversa = inv(matriz)

# Usamos o "inv" para calcular a matriz inversa da matriz criada

print("Matriz original:")

print(matriz)

print("\n Matriz inversa:")

print(matriz_inversa)

Matriz original:
[[ 94  30  21   6  34]
 [ 50  10  11   5  82]
 [  4  77 100  10   2]
 [ 63  83  44  82  34]
 [ 92  41  76  20  80]]

 Matriz inversa:
[[ 1.12181422e-02 -9.37536578e-03 -4.98799301e-03 -9.50841913e-04
   5.37084714e-03]
 [ 1.68016303e-02  2.32275256e-02  1.73912641e-02  3.22195528e-03
  -3.27530192e-02]
 [-1.15803014e-02 -1.63671434e-02 -1.87215650e-03 -3.60348286e-03
   2.32762342e-02]
 [-1.67944351e-02 -1.50690907e-02 -1.35961208e-02  1.16136892e-02
   1.79875380e-02]
 [-6.31180391e-03  1.81936227e-02  2.00074799e-03 -3.78974577e-05
  -3.49985893e-03]]


## Use a funcao de interpolacao cubica de SciPy para interpolar os dados (0, 0),(1, 2),(2, 3),(3, 5),(4, 4).

In [60]:
import numpy as np

from scipy.interpolate import interp1d # Importamos a função "interp1d" do módulo "interpolate" do SciPy para realizar interpolação

# Criamos os valores de x dos pontos fornecidos
x = np.array([0, 1, 2, 3, 4])

# Criamos os valores de y dos pontos fornecidos
y = np.array([0, 2, 3, 5, 4])

# Usamos o "interp1d" para criar uma função de interpolação
# O "kind='cubic'" indica que será utilizada uma interpolação cúbica
funcao_cubica = interp1d(x, y, kind='cubic')

# Criamos novos valores de x para realizar a interpolação
novos_x = np.linspace(0, 4, 100)

# Calculamos os valores de y correspondentes aos novos valores de x
novos_y = funcao_cubica(novos_x)

print("Novos valores de x:")

print(novos_x)

print("\n Valores interpolados de y:")

print(novos_y)

Novos valores de x:
[0.         0.04040404 0.08080808 0.12121212 0.16161616 0.2020202
 0.24242424 0.28282828 0.32323232 0.36363636 0.4040404  0.44444444
 0.48484848 0.52525253 0.56565657 0.60606061 0.64646465 0.68686869
 0.72727273 0.76767677 0.80808081 0.84848485 0.88888889 0.92929293
 0.96969697 1.01010101 1.05050505 1.09090909 1.13131313 1.17171717
 1.21212121 1.25252525 1.29292929 1.33333333 1.37373737 1.41414141
 1.45454545 1.49494949 1.53535354 1.57575758 1.61616162 1.65656566
 1.6969697  1.73737374 1.77777778 1.81818182 1.85858586 1.8989899
 1.93939394 1.97979798 2.02020202 2.06060606 2.1010101  2.14141414
 2.18181818 2.22222222 2.26262626 2.3030303  2.34343434 2.38383838
 2.42424242 2.46464646 2.50505051 2.54545455 2.58585859 2.62626263
 2.66666667 2.70707071 2.74747475 2.78787879 2.82828283 2.86868687
 2.90909091 2.94949495 2.98989899 3.03030303 3.07070707 3.11111111
 3.15151515 3.19191919 3.23232323 3.27272727 3.31313131 3.35353535
 3.39393939 3.43434343 3.47474747 3.51515152

## Resolva o sistema de equacoes 3x + 2y = 5 e x + 4y = 6

In [55]:
import numpy as np
from scipy.linalg import solve # Importamos a função "solve" do módulo "linalg" do SciPy para resolver sistemas de equações lineares

# Criamos a matriz com os coeficientes das equações
matriz = np.array([[3, 2],
                   [1, 4]])

# Criamos o array com os resultados das equações
resultado = np.array([5, 6])

# Usamos o "solve" para encontrar os valores de x e y que satisfazem as duas equações
solucao = solve(matriz, resultado)

print("Valor de x:", solucao[0])

print("Valor de y:", solucao[1])

Valor de x: 0.7999999999999999
Valor de y: 1.3


## Ajuste uma curva quadratica aos pontos (1, 2),(2, 4),(3, 5),(4, 7),(5, 8)

In [59]:
import numpy as np

from scipy.optimize import curve_fit # Importamos a função "curve_fit" do módulo "optimize" do SciPy para ajustar uma curva aos dados

# Criamos os valores de x dos pontos fornecidos
x = np.array([1, 2, 3, 4, 5])

# Criamos os valores de y dos pontos fornecidos
y = np.array([2, 4, 5, 7, 8])

# Criamos a função que representa uma curva quadrática
def funcao_quadratica(x, a, b, c):
    return a * x**2 + b * x + c

# Usamos o "curve_fit" para encontrar os valores de a, b e c que melhor ajustam a curva aos pontos
parametros, _ = curve_fit(funcao_quadratica, x, y)

# Armazenamos os valores encontrados para a, b e c
a, b, c = parametros

print("Valor de a:", a)

print("Valor de b:", b)

print("Valor de c:", c)

print("\nEquação da curva quadrática:")

print(f"y = {a:.2f}x² + {b:.2f}x + {c:.2f}")

Valor de a: -0.07142857142857162
Valor de b: 1.9285714285714297
Valor de c: 0.19999999999999807

Equação da curva quadrática:
y = -0.07x² + 1.93x + 0.20


## Calcule a integral dupla da funcao f(x, y) = xy + x2 no intervalo [0, 2] para x e [0, 1] para y.


In [58]:
from scipy.integrate import dblquad # Importamos a função "dblquad" do módulo "integrate" do SciPy para calcular integrais duplas

# Criamos a função f(x, y) = xy + x²
def funcao(y, x):
    return x * y + x**2

# Usamos o "dblquad" para calcular a integral dupla
# O intervalo de x vai de 0 até 2
# O intervalo de y vai de 0 até 1

integral, erro = dblquad(funcao, 0, 2, 0, 1)

print("Valor da integral:", integral)

Valor da integral: 3.666666666666667


# Encontre os autovalores e autovetores de uma matriz 4x4 de numeros inteiros aleatorios

In [57]:
import numpy as np

from scipy.linalg import eig # Importamos a função "eig" do módulo "linalg" do SciPy para encontrar os autovalores e autovetores

matriz = np.random.randint(1, 101, (4, 4))

# Criamos uma matriz 4x4 com números inteiros aleatórios entre 1 e 100
# (OBS: o número 101 não é incluído)

autovalores, autovetores = eig(matriz)

# Usamos o "eig" para calcular os autovalores e autovetores da matriz
# Os resultados são armazenados nas variáveis "autovalores" e "autovetores"

print("Matriz:")

print(matriz)

print("\nAutovalores:")

print(autovalores)

print("\nAutovetores:")

print(autovetores)

Matriz:
[[ 41  33  98   6]
 [ 21  93  19  95]
 [ 32  61  62  66]
 [100  35  57  23]]

Autovalores:
[211.89604588 +0.j         -6.62648717+51.7163391j
  -6.62648717-51.7163391j  20.35692846 +0.j       ]

Autovetores:
[[ 0.42636887+0.j          0.06939421+0.49999836j  0.06939421-0.49999836j
   0.14936714+0.j        ]
 [ 0.54895035+0.j         -0.43176449-0.31007887j -0.43176449+0.31007887j
  -0.80262848+0.j        ]
 [ 0.52885022+0.j         -0.1916568 -0.10195661j -0.1916568 +0.10195661j
   0.20577485+0.j        ]
 [ 0.48701185+0.j          0.64458446+0.j          0.64458446-0.j
   0.53956806+0.j        ]]


## Resolva a equacao e x − x 2 = 0 para encontrar a raiz mais proxima de x = 1.

In [56]:
import numpy as np # Usamos o numpy e o batizamos de "np" para facilitar o uso de suas funções

from scipy.optimize import fsolve # Importamos a função "fsolve" do módulo "optimize" do SciPy para encontrar raízes de funções

# Criamos a função f(x) = eˣ - x²
def funcao(x):
    return np.exp(x) - x**2

# Usamos o "fsolve" para encontrar a raiz mais próxima de x = 1
# O valor "1" é utilizado como valor inicial para a busca da raiz

raiz = fsolve(funcao, 1)

print("Raiz mais próxima de x = 1:")

print(raiz)

Raiz mais próxima de x = 1:
[-0.70346742]


## Calcule o determinante de uma matriz 6x6 de numeros aleatorios entre -10 e 10

In [62]:
import numpy as np # Usamos o numpy e o batizamos de "np" para facilitar o uso de suas funções

from scipy.linalg import det # Importamos a função "det" do módulo "linalg" do SciPy para calcular o determinante de uma matriz

matriz = np.random.randint(-10, 11, (6, 6))

# Criamos uma matriz 6x6 com números inteiros aleatórios entre -10 e 10
# (OBS: o número 11 não é incluído)

determinante = det(matriz)

# Usamos o "det" para calcular o determinante da matriz

print("Matriz:")

print(matriz)

print("\nDeterminante da matriz:")

print(determinante)

Matriz:
[[  9 -10  -4   4   4   5]
 [ -3   2  -5  -2   5  -1]
 [ -6  -9   1  -8   7  -2]
 [  4  -8  10   4   2  -3]
 [ -6  -8   6  -1   4  -2]
 [ -2   5   4  -7  -1   8]]

Determinante da matriz:
624001.0000000001


## Utilize a funcao de otimizacao multivariada para minimizar f(x, y)= (x−2)2 + (y − 3)2.


In [ ]:
from scipy.optimize import minimize # Importamos a função "minimize" do módulo "optimize" do SciPy para minimizar funções

# Criamos a função f(x, y) = (x - 2)² + (y - 3)²
def funcao(variaveis):
    x, y = variaveis
    return (x - 2)**2 + (y - 3)**2

# Definimos os valores iniciais de x e y
valor_inicial = [0, 0]

# Usamos o "minimize" para encontrar os valores de x e y que minimizam a função
resultado = minimize(funcao, valor_inicial)

print("Valor de x:", resultado.x[0])

print("Valor de y:", resultado.x[1])

print("\nValor mínimo da função:")

print(resultado.fun)

## Calcule a transformada de Fourier inversa de um sinal complexo gerado aleatoriamente

In [ ]:
import numpy as np # Usamos o numpy e o batizamos de "np" para facilitar o uso de suas funções

from scipy.fft import ifft # Importamos a função "ifft" do módulo "fft" do SciPy para calcular a Transformada de Fourier inversa

# Criamos um sinal complexo com números aleatórios
sinal = np.random.rand(10) + 1j * np.random.rand(10)

# Usamos o "ifft" para calcular a Transformada de Fourier inversa do sinal
sinal_inverso = ifft(sinal)

print("Sinal complexo:")

print(sinal)

print("\nTransformada de Fourier inversa:")

print(sinal_inverso)

## Resolva a equacao diferencial de segunda ordem d2y dx2 +y = 0, com condicoes iniciais y(0) = 1 e y′(0) = 0.

In [ ]:
import numpy as np # Usamos o numpy e o batizamos de "np" para facilitar o uso de suas funções

from scipy.integrate import solve_ivp # Importamos a função "solve_ivp" do módulo "integrate" do SciPy para resolver equações diferenciais

# Criamos a função que representa a equação diferencial y'' + y = 0
def equacao(x, y):
    return [y[1], -y[0]]

# Definimos o intervalo de x entre 0 e 10
intervalo = (0, 10)

# Definimos as condições iniciais y(0) = 1 e y'(0) = 0
condicao_inicial = [1, 0]

# Usamos o "solve_ivp" para resolver numericamente a equação diferencial
solucao = solve_ivp(equacao, intervalo, condicao_inicial)

print("Valores de x:")

print(solucao.t)

print("\nValores de y:")

print(solucao.y[0])

## Encontre a raiz c´ubica de 27 utilizando SciPy

In [ ]:
from scipy.special import cbrt # Importamos a função "cbrt" do módulo "special" do SciPy para calcular a raiz cúbica

# Definimos o número que queremos calcular a raiz cúbica
numero = 27

# Usamos o "cbrt" para calcular a raiz cúbica do número
raiz_cubica = cbrt(numero)

print("Raiz cúbica de 27:")

print(raiz_cubica)

## Interpole os valores de uma funcao f(x) = x2 nos pontos [1, 2, 3, 4, 5] utilizando spline cubica.

In [ ]:
import numpy as np # Usamos o numpy e o batizamos de "np" para facilitar o uso de suas funções

from scipy.interpolate import CubicSpline # Importamos a função "CubicSpline" do módulo "interpolate" do SciPy para realizar interpolação por spline cúbica

# Criamos os pontos de x fornecidos
x = np.array([1, 2, 3, 4, 5])

# Calculamos os valores de y utilizando a função f(x) = x²
y = x**2

# Usamos o "CubicSpline" para criar uma função de interpolação por spline cúbica
spline = CubicSpline(x, y)

# Criamos novos valores de x entre 1 e 5 para realizar a interpolação
novos_x = np.linspace(1, 5, 20)

# Calculamos os valores interpolados de y para os novos valores de x
novos_y = spline(novos_x)

print("Valores originais de x:")

print(x)

print("\nValores originais de y:")

print(y)

print("\nValores interpolados:")

print(novos_y)

## Realize a transformada de Fourier de um sinal discreto composto de senos e cossenos.

In [ ]:
import numpy as np # Usamos o numpy e o batizamos de "np" para facilitar o uso de suas funções

from scipy.fft import fft # Importamos a função "fft" do módulo "fft" do SciPy para calcular a Transformada de Fourier

# Criamos 100 pontos discretos
n = np.arange(100)

# Criamos um sinal composto por seno e cosseno
sinal = np.sin(2 * np.pi * 5 * n / 100) + np.cos(2 * np.pi * 10 * n / 100)

# Usamos o "fft" para calcular a Transformada de Fourier do sinal
transformada = fft(sinal)

# Calculamos a intensidade das frequências presentes no sinal
magnitude = np.abs(transformada)

print("Sinal discreto:")

print(sinal)

print("\nTransformada de Fourier:")

print(transformada)

print("\nMagnitude da Transformada:")

print(magnitude)

## Resolva um sistema de equacoes lineares com tres variaveis utilizando SciPy.


In [ ]:
import numpy as np # Usamos o numpy e o batizamos de "np" para facilitar o uso de suas funções

from scipy.linalg import solve # Importamos a função "solve" do módulo "linalg" do SciPy para resolver sistemas de equações lineares

# Criamos a matriz com os coeficientes das três equações
matriz = np.array([[1, 1, 1],
                   [2, 1, -1],
                   [1, 2, 1]])

# Criamos o array com os resultados das três equações
resultado = np.array([6, 3, 8])

# Usamos o "solve" para encontrar os valores de x, y e z
solucao = solve(matriz, resultado)

print("Valor de x:", solucao[0])

print("Valor de y:", solucao[1])

print("Valor de z:", solucao[2])